CREATE TABLE TESTER (
	OperID INTEGER PRIMARY KEY,
    FName VARCHAR(20),
    MidInit CHAR(1),
    LName VARCHAR(20),
    TeamRole VARCHAR(20)
);

CREATE TABLE EXPERIMENT (
	ExpID INTEGER PRIMARY KEY,
    ExpName VARCHAR(50),
    ExpDescr VARCHAR(300),
    SweepVar VARCHAR(20),
    MeasVar VARCHAR(20),
    Instrument VARCHAR(50)
);

CREATE TABLE DEVICE (
	LotID INTEGER NOT NULL,
    DeviceName VARCHAR(50) NOT NULL,
    DevDescr VARCHAR(300),
    TestByDate DATETIME,
    PRIMARY KEY (LotID, DeviceName)
);

ALTER TABLE EXPERIMENT
ADD COLUMN LotID INTEGER NOT NULL;

ALTER TABLE EXPERIMENT
ADD COLUMN DeviceName VARCHAR(50);

ALTER TABLE EXPERIMENT
ADD CONSTRAINT fk_device
FOREIGN KEY (LotID, DeviceName) REFERENCES DEVICE(LotID, DeviceName);

CREATE TABLE RESULTS (
    ExpID INTEGER NOT NULL,
    SweepValues DOUBLE PRECISION,
    MeasValues DOUBLE PRECISION,
    CONSTRAINT fk_experiment FOREIGN KEY (ExpID)
		REFERENCES EXPERIMENT(ExpID)
);